apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    app: mongo
data:
  MONGO_INITDB_DATABASE: censusdb
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongo-credentials
  labels:
    app: mongo
stringData:
  user: admin
  password: admin
