apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.7
          imagePullPolicy: IfNotPresent
          args: [ "--replSet", "rs0", "--keyFile", "/mongo-keys/mongodb.key", "--bind_ip_all" ]
          ports:
            - name: db
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: mongo-config
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
            - name: init-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
            - name: keys-volume
              mountPath: /mongo-keys
          livenessProbe:
            tcpSocket:
              port: db
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: db
            initialDelaySeconds: 5
            periodSeconds: 10
      initContainers:
        - name: init-scripts
          image: mongo-dbinit:dev
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: init-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
        - name: key-generator
          image: mongo-key-generator:dev
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: keys-volume
              mountPath: /mongo-keys
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-volume-claim
        - name: init-scripts-volume
          emptyDir:
            sizeLimit: 1Gi
        - name: keys-volume
          emptyDir:
            sizeLimit: 1Gi
