kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-volume
  labels:
    app: mongo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/census/mongo"
  claimRef:
    namespace: default
    name: mongo-volume-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-volume-claim
  labels:
    app: mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
