apiVersion: v1
kind: ConfigMap
metadata:
  name: census-config
  labels:
    app: census
data:
  config.json: |-
    {
      "global": {
        "database": "mongo"
      },
      "httpServer": {
        "port": 8080
      },
      "postgres": {
        "host": "postgres",
        "port": 5432,
        "database": "censusdb",
        "verifyTls": false
      },
      "mongo": {
        "host": "mongo",
        "port": 27017,
        "replicaSet": "rs0",
        "database": "censusdb",
        "verifyTls": false
      }
    }
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: census-secret
  labels:
    app: census
stringData:
  config.json: |-
    {
      "postgres": {
        "user": "admin",
        "password": "admin"
      },
      "mongo": {
        "user": "admin",
        "password": "admin"
      } 
    }
