apiVersion: v1
kind: ConfigMap
metadata:
  name: census-config
  labels:
    app: census
data:
  config.json: |-
    {
      "httpServer": {
        "port": 8080
      },
      "postgres": {
        "host": "postgres",
        "port": 5432,
        "database": "censusdb"
      }
    }
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: census-secret
  labels:
    app: census
stringData:
  config.json: |-
    {
      "postgres": {
        "user": "admin",
        "password": "admin"
      }
    }
