# This file is not actually deployed. It's only provided to show how the census secret resource is defined.
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    app: census
  name: census-cert
data:
  tls.crt: --TLS_CERT_DATA--
  tls.key: --TLS_CERT_KEY--
