apiVersion: v1
kind: Service
metadata:
  name: census
  labels:
    app: census
spec:
  selector:
    app: census
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
